{% set version = "580.0.0" %}

package:
  name: google-cloud-sdk
  version: {{ version }}

source:
  url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-{{ version }}-linux-x86_64.tar.gz  # [linux and x86_64]
  sha256: 8b871ceb04019d5f8cb67fb1dba0deb3892572e48505599eac1eec14eb00402f  # [linux and x86_64]
  url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-{{ version }}-linux-arm.tar.gz  # [linux and aarch64]
  sha256: f8db741f4258224aa9c05f4756d0920a81753cb5d2d944b2d1589d094b89861f  # [linux and aarch64]
  url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-{{ version }}-darwin-x86_64.tar.gz  # [osx and x86_64]
  sha256: 9688006c182a95b83a21c0246216b2f5439fb71eb7d70b526a9f480dd9ce1317  # [osx and x86_64]
  url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-{{ version }}-darwin-arm.tar.gz  # [osx and arm64]
  sha256: 4f704fd6e2f918c667da53c96304fa4c831a8a4e84f3c24c4b27ad0880d8f3af  # [osx and arm64]

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
  run:
    - python

test:
  commands:
    - gcloud version
    - gsutil help  # [py2k]
    - gcloud components list

about:
  home: https://cloud.google.com/sdk/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Command-line interface for Google Cloud Platform products and services

extra:
  recipe-maintainers:
    - chapmanb
    - scopatz
    - nehaljwani
