{% set version = "570.0.0" %}

package:
  name: google-cloud-sdk
  version: {{ version }}

source:
  url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-{{ version }}-linux-x86_64.tar.gz  # [linux and x86_64]
  sha256: b35c621a75d8e176b6b9f5629896b28a18fe3f2de6b147fc7c96d5e09921a2e3  # [linux and x86_64]
  url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-{{ version }}-linux-arm.tar.gz  # [linux and aarch64]
  sha256: ca0d6d789d6677b2d8b460b24a5df4d8298f015c642a85a66aaa1a0ffe9ebe20  # [linux and aarch64]
  url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-{{ version }}-darwin-x86_64.tar.gz  # [osx and x86_64]
  sha256: ad2aad8f8e03d06a69b4d0aea28938bb34bb41f152093bb8ca1f8c8b64ce66be  # [osx and x86_64]
  url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-{{ version }}-darwin-arm.tar.gz  # [osx and arm64]
  sha256: faf31849cb6737fe5a2d4e56ab7f3941ac7107908a7b6c9ba6099a4ac95fc66e  # [osx and arm64]

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
  run:
    - python

test:
  commands:
    - gcloud version
    - gsutil help  # [py2k]
    - gcloud components list

about:
  home: https://cloud.google.com/sdk/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Command-line interface for Google Cloud Platform products and services

extra:
  recipe-maintainers:
    - chapmanb
    - scopatz
    - nehaljwani
