{% set version = "561.0.0" %}

package:
  name: google-cloud-sdk
  version: {{ version }}

source:
  url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-{{ version }}-linux-x86_64.tar.gz  # [linux and x86_64]
  sha256: cce6feba11949eb76b118faf9c7e67709c3b1bcd5519cb0acfb72ddb8ece917e  # [linux and x86_64]
  url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-{{ version }}-linux-arm.tar.gz  # [linux and aarch64]
  sha256: 559628216ed82bbf1c1db39d451743a494cb9a5130488591c73287fa95453f1a  # [linux and aarch64]
  url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-{{ version }}-darwin-x86_64.tar.gz  # [osx and x86_64]
  sha256: 1341922d82d7bfba1dceaef239004c0f3ac32ac5dfa4ddb29cda7398caf7ce96  # [osx and x86_64]
  url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-{{ version }}-darwin-arm.tar.gz  # [osx and arm64]
  sha256: 87f2ead5ff77eca532bb43ae27cbe883e9c8701edf2d01f16038b847c57fc581  # [osx and arm64]

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
  run:
    - python

test:
  commands:
    - gcloud version
    - gsutil help  # [py2k]
    - gcloud components list

about:
  home: https://cloud.google.com/sdk/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Command-line interface for Google Cloud Platform products and services

extra:
  recipe-maintainers:
    - chapmanb
    - scopatz
    - nehaljwani
