{% set version = "546.0.0" %}

package:
  name: google-cloud-sdk
  version: {{ version }}

source:
  url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-{{ version }}-linux-x86_64.tar.gz  # [linux and x86_64]
  sha256: fb273887b6755ba68fb5f47ffc9f1e86b78386a767bd7d6618b1b6bfa5e33fa3  # [linux and x86_64]
  url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-{{ version }}-linux-arm.tar.gz  # [linux and aarch64]
  sha256: 75bc1e1e719b22e6c87509d5d71ad5552edf0c158fcb54b9496c3f2f0da294cb  # [linux and aarch64]
  url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-{{ version }}-darwin-x86_64.tar.gz  # [osx and x86_64]
  sha256: 67894d41595b2e54a1463315186e97d6aec7c221a0cf2881c6a86f0191784b71  # [osx and x86_64]
  url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-{{ version }}-darwin-arm.tar.gz  # [osx and arm64]
  sha256: f5b48a5954cf3c9316537f022d9da39b5ea5dfedd9911bcf86a2cc131950581c  # [osx and arm64]
  url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-{{ version }}-windows-x86_64.zip  # [win and x86_64]
  sha256: b073ad131b897c9d18f525a1e0ecc4b911fdf517abbe4a6bcfed893a55fffeaf  # [win and x86_64]

build:
  number: 1
  noarch: generic

requirements:

  host:
    - python {{ python_min }}.*

  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  commands:
    - gcloud version
    - gsutil help  # [py2k]
    - gcloud components list

about:
  home: https://cloud.google.com/sdk/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Command-line interface for Google Cloud Platform products and services

extra:
  recipe-maintainers:
    - chapmanb
    - scopatz
    - nehaljwani
