{% set version = "399.0.0" %}

package:
  name: google-cloud-sdk
  version: {{ version }}

source:
  url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-{{ version }}-linux-x86_64.tar.gz  # [linux]
  sha256: ef4c89b3533303a3836f163957dfdad163904a8ad48e0bf34fe1d0afde916429  # [linux]
  url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-{{ version }}-darwin-x86_64.tar.gz  # [osx and build_platform == "osx-64"]
  sha256: 8f73f3723dbee24e6154baedfea3e488a1983c1114a54e2c4170061a64a66324  # [osx and build_platform == "osx-64"]
  url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-{{ version }}-darwin-arm.tar.gz  # [osx and build_platform == "osx-arm64"]
  sha256: 50c9566e49b24dd4ef2101ddfb1925feb9f9be38df9904c9fed27e731fd48adc  # [osx and build_platform == "osx-arm64"]

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
  run:
    - python

test:
  commands:
    - gcloud version
    - gsutil help  # [py2k]
    - gcloud components list

about:
  home: https://cloud.google.com/sdk/
  license: Apache v2.0
  license_family: Apache
  license_file: LICENSE
  summary: Command-line interface for Google Cloud Platform products and services

extra:
  recipe-maintainers:
    - chapmanb
    - scopatz
    - nehaljwani
