{% set version = "398.0.0" %}

package:
  name: google-cloud-sdk
  version: {{ version }}

source:
  url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-{{ version }}-linux-x86_64.tar.gz  # [linux]
  sha256: ebbf5b72ee520f0a5a1fa63e35c4ea4c9eb67edb55e9aef3dc4b335f8f90b24f  # [linux]
  url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-{{ version }}-darwin-x86_64.tar.gz  # [osx and build_platform == "osx-64"]
  sha256: 7eeed24f2060995a9e70cc4dfa578e2c2143a51545e2d995b0f9f62c846acb89  # [osx and build_platform == "osx-64"]
  url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-{{ version }}-darwin-arm.tar.gz  # [osx and build_platform == "osx-arm64"]
  sha256: 62864574e5f1dd6f010a6a393edd02a9a31dce5cd06f0242cdda76e0268a0c4d  # [osx and build_platform == "osx-arm64"]

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
  run:
    - python

test:
  commands:
    - gcloud version
    - gsutil help  # [py2k]
    - gcloud components list

about:
  home: https://cloud.google.com/sdk/
  license: Apache v2.0
  license_family: Apache
  license_file: LICENSE
  summary: Command-line interface for Google Cloud Platform products and services

extra:
  recipe-maintainers:
    - chapmanb
    - scopatz
    - nehaljwani
