context:
  name: google-cloud-sdk
  version: "542.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - if: linux and x86_64
    then:
      url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${{ version }}-linux-x86_64.tar.gz
      sha256: 6ac032650f507e61cf0b68a462be7e97edc9352cb3b95ce9a0d32cd8a4cfdfd5
  - if: linux and aarch64
    then:
      url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${{ version }}-linux-arm.tar.gz
      sha256: 6b732c2e38da8d03395688fd4460b6d28a63a6d6d140836f4ecc1eee198be5e7
  - if: osx and x86_64
    then:
      url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${{ version }}-darwin-x86_64.tar.gz
      sha256: aedd2c745a4cc4217deed66991ee864ccc6fb35c51f4d71c125ccaf512247ba3
  - if: osx and arm64
    then:
      url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${{ version }}-darwin-arm.tar.gz
      sha256: 8430b9872b18f829e2b588e94809f898820e128267cdf01eac4f62695dfd0396
  - if: win and x86_64
    then:
      url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-{{ version }}-windows-x86_64.zip
      sha256: e44ccbac3087ca97650f68c4b0077d26fd3ce2b1e8278de0797e2e6ba20d8e6d

build:
  number: 1
  noarch: generic

requirements:

  host:
    - python {{ python_min }}.*
  run:
    - python >={{ python_min }}

tests:
    - script:
      - gcloud version
      - gcloud components list

about:
  homepage: https://cloud.google.com/sdk/
  license: Apache-2.0
  license_file: LICENSE
  summary: Command-line interface for Google Cloud Platform products and services

extra:
  recipe-maintainers:
    - chapmanb
    - scopatz
    - nehaljwani


