appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: CgdLSve0a20CoAweF0m7JrzBiAp0opPC4oEEWPQ9l4nP1u6P9HhLpw/jduzPUIFnaiStvbkhm/Bb6pzHZNA/WquGmZUBcYtvJa3ts+31f6PpyPofJhPvF6pOPKwLC7WHu6xmGq5vwFAgfhAxwxVa50JRKx2jJ2+r1Axkeg6+dQAtvJ2Usgyv04G4n1qUTJvfDpUlNEXYLQ69tsQ1taOO5u2xpYD5tacWeZZZgFahcczYxdOg/D7xo1RGYmPKh23lLlO9KJ56QMbey4f/hOYlIRMZ8s+0bQaEQJnkpvmngJngnd3AM9DMoznA7j7oWb4Xw7RxSwYD7b9N55lCHnYoMhLrUex0etyzzE3/60nHi/PyMoyeScdKrWIPwW1gQBne5YfNmFlLAWSpHtUbeaDlW8eQZoBbCyreETPjFEPHn1SruJE3UQuENFXl8ZvhGasjK1QOpo1sIRNZOMS+cds2M3+T4Ch00LribO6hCf2JWNaNeYIrmyNJPtE0umuIq213OixHYlG7VVNh5cO8P+VqWQrRenXhvG6L96vGL8MReojJOZAxl6SVa6BjUrRGormDVTQzKYQHppH47v82bHIL8n9wBoQI9kgTaKaRAplOvjHgQFhUUYq3MKVB6SB8cy/S/Lrub9zNNeUOYxYs9tY7JMFlM4kQIR/nGAimBfD1+ZA=}
bot:
  automerge: true
conda_forge_output_validation: true
